// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A game recommendation AI agent based on search history.
 *
 * - getGameRecommendations - A function that handles the game recommendation process.
 * - GetGameRecommendationsInput - The input type for the getGameRecommendations function.
 * - GetGameRecommendationsOutput - The return type for the getGameRecommendations function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GetGameRecommendationsInputSchema = z.object({
  searchHistory: z.array(z.string()).describe('The user search history.'),
});
export type GetGameRecommendationsInput = z.infer<typeof GetGameRecommendationsInputSchema>;

const GetGameRecommendationsOutputSchema = z.object({
  recommendations: z.array(z.string()).describe('Recommended games based on search history.'),
});
export type GetGameRecommendationsOutput = z.infer<typeof GetGameRecommendationsOutputSchema>;

export async function getGameRecommendations(input: GetGameRecommendationsInput): Promise<GetGameRecommendationsOutput> {
  return getGameRecommendationsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'gameRecommendationsPrompt',
  input: {schema: GetGameRecommendationsInputSchema},
  output: {schema: GetGameRecommendationsOutputSchema},
  prompt: `Based on the user's search history: {{searchHistory}},
  recommend a list of games that the user might enjoy. Return the recommendations as a list of strings.
  If the user has no search history, return an empty list.`,
});

const getGameRecommendationsFlow = ai.defineFlow(
  {
    name: 'getGameRecommendationsFlow',
    inputSchema: GetGameRecommendationsInputSchema,
    outputSchema: GetGameRecommendationsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
