// Games configuration - metadata for all 30 games

import { Game, CategoryInfo, GameCategory } from '@/types/game';

export const CATEGORIES: CategoryInfo[] = [
    {
        id: 'puzzle',
        name: 'Puzzle',
        description: 'Brain-teasing challenges',
        icon: '🧩',
        color: 'from-purple-500 to-pink-500',
    },
    {
        id: 'arcade',
        name: 'Arcade',
        description: 'Classic arcade action',
        icon: '🎮',
        color: 'from-blue-500 to-cyan-500',
    },
    {
        id: 'action',
        name: 'Action',
        description: 'Fast-paced excitement',
        icon: '⚡',
        color: 'from-orange-500 to-red-500',
    },
    {
        id: 'skill',
        name: 'Skill',
        description: 'Test your abilities',
        icon: '⌨️',
        color: 'from-green-500 to-emerald-500',
    },
    {
        id: 'classic',
        name: 'Classic',
        description: 'Timeless favorites',
        icon: '🎯',
        color: 'from-yellow-500 to-amber-500',
    },
    {
        id: 'trivia',
        name: 'Trivia',
        description: 'Knowledge games',
        icon: '❓',
        color: 'from-indigo-500 to-violet-500',
    },
];

export const GAMES: Game[] = [
    {
        id: 1,
        slug: 'candy-crush',
        title: 'Candy Crush',
        description: 'Match three or more candies to score points in this addictive puzzle game.',
        category: 'puzzle',
        difficulty: 3,
        thumbnail: '/thumbnails/candy-crush.png',
        controls: ['Click/tap to select a candy', 'Click adjacent candy to swap', 'Match 3+ to score'],
        featured: true,
    },
    {
        id: 2,
        slug: 'archery',
        title: 'Archery',
        description: 'Test your aim and hit the target in this precision archery game.',
        category: 'action',
        difficulty: 3,
        thumbnail: '/thumbnails/archery.png',
        controls: ['Click and hold to aim', 'Release to shoot', 'Hit the bullseye for max points'],
    },
    {
        id: 3,
        slug: 'speed-typing',
        title: 'Speed Typing',
        description: 'Race against time to type words as fast as you can.',
        category: 'skill',
        difficulty: 3,
        thumbnail: '/thumbnails/speed-typing.png',
        controls: ['Type the displayed words', 'Complete before time runs out'],
    },
    {
        id: 4,
        slug: 'breakout',
        title: 'Breakout',
        description: 'Classic brick-breaking arcade game. Destroy all bricks to win!',
        category: 'arcade',
        difficulty: 4,
        thumbnail: '/thumbnails/breakout.png',
        controls: ['Move paddle with mouse/keyboard', 'Bounce ball to break bricks'],
        featured: true,
    },
    {
        id: 5,
        slug: 'minesweeper',
        title: 'Minesweeper',
        description: 'Clear the minefield without triggering any mines.',
        category: 'puzzle',
        difficulty: 4,
        thumbnail: '/thumbnails/minesweeper.png',
        controls: ['Left click to reveal', 'Right click to flag mines'],
        featured: true,
    },
    {
        id: 6,
        slug: 'tower-blocks',
        title: 'Tower Blocks',
        description: 'Stack blocks as high as you can without toppling the tower.',
        category: 'arcade',
        difficulty: 4,
        thumbnail: '/thumbnails/tower-blocks.png',
        controls: ['Click/tap to drop block', 'Time it perfectly to stack'],
    },
    {
        id: 7,
        slug: 'ping-pong',
        title: 'Ping Pong',
        description: 'Classic table tennis against an AI opponent.',
        category: 'arcade',
        difficulty: 3,
        thumbnail: '/thumbnails/ping-pong.png',
        controls: ['Move paddle with mouse/keyboard', 'Score 10 points to win'],
    },
    {
        id: 8,
        slug: 'tetris',
        title: 'Tetris',
        description: 'The classic block-stacking puzzle game that never gets old.',
        category: 'arcade',
        difficulty: 4,
        thumbnail: '/thumbnails/tetris.png',
        controls: ['Arrow keys to move', 'Up arrow to rotate', 'Space to hard drop'],
        featured: true,
    },
    {
        id: 9,
        slug: 'tilting-maze',
        title: 'Tilting Maze',
        description: 'Guide the ball through the maze using device motion or controls.',
        category: 'skill',
        difficulty: 5,
        thumbnail: '/thumbnails/tilting-maze.png',
        controls: ['Tilt device or use arrow keys', 'Navigate ball to the goal'],
    },
    {
        id: 10,
        slug: 'memory-card',
        title: 'Memory Card',
        description: 'Flip cards and match pairs in this classic memory game.',
        category: 'puzzle',
        difficulty: 2,
        thumbnail: '/thumbnails/memory-card.png',
        controls: ['Click to flip a card', 'Find all matching pairs'],
    },
    {
        id: 11,
        slug: 'rock-paper-scissors',
        title: 'Rock Paper Scissors',
        description: 'The timeless hand game against the computer.',
        category: 'classic',
        difficulty: 1,
        thumbnail: '/thumbnails/rock-paper-scissors.png',
        controls: ['Click your choice', 'Best of 5 wins'],
    },
    {
        id: 12,
        slug: 'number-guessing',
        title: 'Number Guessing',
        description: 'Guess the secret number with hints to guide you.',
        category: 'trivia',
        difficulty: 1,
        thumbnail: '/thumbnails/number-guessing.png',
        controls: ['Type a number', 'Use hints to narrow down'],
    },
    {
        id: 13,
        slug: 'tic-tac-toe',
        title: 'Tic Tac Toe',
        description: 'Classic X and O game against the computer.',
        category: 'classic',
        difficulty: 1,
        thumbnail: '/thumbnails/tic-tac-toe.png',
        controls: ['Click a square to place mark', 'Get 3 in a row to win'],
        featured: true,
    },
    {
        id: 14,
        slug: 'snake',
        title: 'Snake',
        description: 'Grow your snake by eating food without hitting walls or yourself.',
        category: 'arcade',
        difficulty: 3,
        thumbnail: '/thumbnails/snake.png',
        controls: ['Arrow keys to move', 'Eat food to grow'],
        featured: true,
    },
    {
        id: 15,
        slug: 'connect-four',
        title: 'Connect Four',
        description: 'Drop discs and be the first to connect four in a row.',
        category: 'classic',
        difficulty: 2,
        thumbnail: '/thumbnails/connect-four.png',
        controls: ['Click column to drop disc', 'Connect 4 to win'],
    },
    {
        id: 16,
        slug: 'insect-catch',
        title: 'Insect Catch',
        description: 'Click on insects before they escape.',
        category: 'action',
        difficulty: 2,
        thumbnail: '/thumbnails/insect-catch.png',
        controls: ['Click on insects to catch them', 'Score as many as possible'],
    },
    {
        id: 17,
        slug: 'typing-game',
        title: 'Typing Game',
        description: 'Improve your typing speed with this fun challenge.',
        category: 'skill',
        difficulty: 3,
        thumbnail: '/thumbnails/typing-game.png',
        controls: ['Type falling words', 'Clear words before they reach bottom'],
    },
    {
        id: 18,
        slug: 'hangman',
        title: 'Hangman',
        description: 'Guess the word letter by letter before running out of tries.',
        category: 'trivia',
        difficulty: 2,
        thumbnail: '/thumbnails/hangman.png',
        controls: ['Click letters to guess', '6 wrong guesses and you lose'],
    },
    {
        id: 19,
        slug: 'flappy-bird',
        title: 'Flappy Bird',
        description: 'Navigate the bird through pipes by timing your taps.',
        category: 'arcade',
        difficulty: 4,
        thumbnail: '/thumbnails/flappy-bird.png',
        controls: ['Click/tap to flap', 'Avoid pipes'],
    },
    {
        id: 20,
        slug: 'crossy-road',
        title: 'Crossy Road',
        description: 'Cross busy roads and rivers without getting hit.',
        category: 'arcade',
        difficulty: 4,
        thumbnail: '/thumbnails/crossy-road.png',
        controls: ['Arrow keys or swipe to move', 'Avoid cars and obstacles'],
    },
    {
        id: 21,
        slug: '2048',
        title: '2048',
        description: 'Slide tiles and combine numbers to reach 2048.',
        category: 'puzzle',
        difficulty: 3,
        thumbnail: '/thumbnails/2048.png',
        controls: ['Arrow keys to slide tiles', 'Combine same numbers'],
    },
    {
        id: 22,
        slug: 'dice-roll',
        title: 'Dice Roll',
        description: 'Roll the dice and test your luck.',
        category: 'classic',
        difficulty: 1,
        thumbnail: '/thumbnails/dice-roll.png',
        controls: ['Click to roll dice', 'See your result'],
    },
    {
        id: 23,
        slug: 'shape-clicker',
        title: 'Shape Clicker',
        description: 'Click on shapes as fast as you can.',
        category: 'action',
        difficulty: 2,
        thumbnail: '/thumbnails/shape-clicker.png',
        controls: ['Click shapes before they disappear', 'Score as many as possible'],
    },
    {
        id: 24,
        slug: 'typing-challenge',
        title: 'Typing Challenge',
        description: 'Alternative typing game with unique challenges.',
        category: 'skill',
        difficulty: 3,
        thumbnail: '/thumbnails/typing-challenge.png',
        controls: ['Type displayed text accurately', 'Beat the timer'],
    },
    {
        id: 25,
        slug: 'speak-number-guessing',
        title: 'Speak Number Guessing',
        description: 'Use your voice to guess the secret number.',
        category: 'skill',
        difficulty: 3,
        thumbnail: '/thumbnails/speak-number.png',
        controls: ['Speak your guess', 'Follow audio hints'],
    },
    {
        id: 26,
        slug: 'fruit-slicer',
        title: 'Fruit Slicer',
        description: 'Slice fruits as they fly across the screen.',
        category: 'action',
        difficulty: 4,
        thumbnail: '/thumbnails/fruit-slicer.png',
        controls: ['Swipe to slice fruits', 'Avoid bombs'],
    },
    {
        id: 27,
        slug: 'quiz',
        title: 'Quiz Game',
        description: 'Test your knowledge with trivia questions.',
        category: 'trivia',
        difficulty: 2,
        thumbnail: '/thumbnails/quiz.png',
        controls: ['Click to select answer', 'Answer correctly to score'],
    },
    {
        id: 28,
        slug: 'emoji-catcher',
        title: 'Emoji Catcher',
        description: 'Catch falling emojis before they disappear.',
        category: 'action',
        difficulty: 2,
        thumbnail: '/thumbnails/emoji-catcher.png',
        controls: ['Move to catch emojis', 'Catch the right ones'],
    },
    {
        id: 29,
        slug: 'whack-a-mole',
        title: 'Whack-A-Mole',
        description: 'Whack moles as they pop up from their holes.',
        category: 'arcade',
        difficulty: 2,
        thumbnail: '/thumbnails/whack-a-mole.png',
        controls: ['Click moles when they appear', 'Score as many as possible'],
    },
    {
        id: 30,
        slug: 'simon-says',
        title: 'Simon Says',
        description: 'Follow the pattern and repeat the sequence.',
        category: 'classic',
        difficulty: 3,
        thumbnail: '/thumbnails/simon-says.png',
        controls: ['Watch the pattern', 'Repeat by clicking colors'],
    },
];

// Helper functions
export function getGameBySlug(slug: string): Game | undefined {
    return GAMES.find((game) => game.slug === slug);
}

export function getGamesByCategory(category: GameCategory): Game[] {
    return GAMES.filter((game) => game.category === category);
}

export function getFeaturedGames(): Game[] {
    return GAMES.filter((game) => game.featured);
}

export function getCategoryInfo(categoryId: GameCategory): CategoryInfo | undefined {
    return CATEGORIES.find((cat) => cat.id === categoryId);
}

export function searchGames(query: string): Game[] {
    const lowerQuery = query.toLowerCase();
    return GAMES.filter(
        (game) =>
            game.title.toLowerCase().includes(lowerQuery) ||
            game.description.toLowerCase().includes(lowerQuery) ||
            game.category.toLowerCase().includes(lowerQuery)
    );
}
